# Pull base image 
FROM tomcat:8-jre8
#FROM openjdk:8u111-jdk-alpine

# Maintainer 
 
COPY ./dockerproj.war /usr/local/tomcat/webapps

#ADD /server/1.0-SNAPSHOT/server-1.0-SNAPSHOT.jar app.jar 
#ENTRYPOINT ["java","-jar","/app.jar"] 

